### ISSUE TITLE
Cannot read selected line with company-mode

### ISSUE THREAD

**Issue by brabalan** [n3mo/cyberpunk-theme.el#12]
I just enabled company-mode and when a completion is proposed, I cannot read the first line:

![screen shot 2014-06-10 at 15 04 17](https://cloud.githubusercontent.com/assets/1021637/3230279/4333d352-f0a1-11e3-9ad0-a4abcf1b1c83.png)

I've restarted emacs to make sure there was no customization involved, and I get the same thing. Is it possible to make the text more visible on the pink background?

**Comment by nivekuil** [comment]
I have a similar issue that maybe the above poster was referring to, where the autocomplete text is the same color as the background. Here's a screenshot with emacs -q, then (package-initialize), (company-mode), and (load-theme 'cyberpunk): http://i.imgur.com/iNyvaqb.png

**Comment by n3mo** [comment]
Nivehuil: Thanks for the solution! Merged
