### ISSUE TITLE
support for the new version of magit (2.1.0)?

### ISSUE THREAD

**Issue by tee3** [n3mo/cyberpunk-theme.el#16]
FYI: There is a new version of magit coming and it would be really nice to have cyberpunk theme support!å  Please see https://github.com/magit/magit/issues/1922#issuecomment-116123170.

**Comment by n3mo** [comment]
Thanks for the heads up. I've heard from others too and I do plan to update cyberpunk asap. Cheers!

**Comment by tee3** [comment]
Cheers!

**Comment by n3mo** [comment]
Support (using default faces) for magit 2.1.0 was added 17 days ago. I will take another look at this soon to potentially adjust some things to make the experience more  cyberpunk-y. Until then...

**Comment by dubiousdavid** [comment]
Any updates on this?

**Comment by n3mo** [comment]
Sadly, no, there are no updates as of yet. For now, cyberpunk falls back to the default coloring of magit 2+. I've had a new job and other more pressing projects tying up my free time. This has not left my radar however. Apologies for the delay :(

**Comment by n3mo** [comment]
I'm happy to report that I've (finally) addressed the "new" magit--let me know what you think. I've also reworked some of the theme to make it more consistent across more modes (including new support for racket-mode and eshell). If you run into problems, or find the new magit look problematic, feel free to reopen the issue.

Cheers!

**Comment by tee3** [comment]
This looks much better for most everything in magit, thanks for your effort in updating it!  

However, I do feel that there might be room for improvement in the handling of diffs within magit buffers containing diffs.

For a normal diff, cyberpunk has a nice simple green / red *foreground* for added / deleted lines, which is much clearer than the default emacs theme for a black terminal (thanks!).  In magit's buffers containing diffs (`magit-diff`, `magit-rev`, others), cyberpunk has a greenish / purplish *background* for added deleted lines and a pretty heavy gray *background* for selected regions.  I find it hard to read the diffs and near impossible to read when a diff is actually selected.  Note that this is different from the current default theme, but very similar to many other magit themes, but it doesn't seem like a cyberpunk scheme to me.

I realize a `magit-rev` buffer is more complicated than a `diff-mode` buffer and the red / green might not work well there, but something lightweight and consistent with the rest of the cyberpunk colors might be nicer.  This might be something like an electric greenish / reddish foreground color that works with the rest of the theme for the diffs and a very light highlight for the background for selected sections.  The `grandshell-theme` has a nice and readable magit diff mode that might be inspiring (though the colors aren't as much to my liking as cyberpunk).

You're the expert, so if this is the current diff scheme is your choice, I'm sure I'll eventually see the beauty of it :)  Again, thanks for this color theme, I use it daily and it makes me happy.

**Comment by n3mo** [comment]
Despite using magit in some capacity almost daily, I must admit that I don't fully make use of its functionality--so there's a good chance that I've borked something without being aware. That said, through either ignorance or a different .emacs.d configuration side-effect, I am unable to generate the problematic coloring you describe for magit diffs. In short, `M-x magit-diff` and `M-x magit-status d u` lead to difff buffers with green for added lines and red for removed lines. 

Can you possibly provide a context and sequence of commands that produce the offending coloring?

**Comment by n3mo** [comment]
It seems that a few more magit diff faces are available that cyberpunk is not using: `magit-diff-added`, `magit-diff-added-highlight`, and `smerge-refined-added`. These are meant to complement the standard `diff-added`, `diff-changed`, and `diff-removed` faces responsible for coloring standard diff buffers. The latter three faces are indeed set by cyberpunk, which magit appears to fall back to... at least for me. It is curious why it's not working for you...

**Comment by tee3** [comment]
Hi @n3mo, thanks for checking this out.  I'm not sure what's going on either, but you got me interested in actually looking at the details.  In my setup, the `magit-diff-added-highlight` face is set by cyberpunk to the color observed below.  Disabling cyberpunk results in the theme changing back to it's default value.  These variables are used in `magit`'s default theme as well as in cyberpunk for me.  They are not set in `cyberpunk-theme.el`, so I don't know where they come from.  As I said before, these same colors are used for other themes, but I don't know where they come from.  Is there some kind of default behind themes?

I've attached a screenshot of what I could gather about my system.  The `junk` buffer is the contents of the `*magit-revision: example` buffer in `diff-mode`.  Note that the `magit-diff-added-highlight` are not even shown in the `describe-theme` buffer.

[screen shot 2015-12-16 at 7 20 08 am](https://cloud.githubusercontent.com/assets/231540/11840694/d40787e2-a3c5-11e5-8dc6-02cd0274ae74.png)

**Comment by tee3** [comment]
Actually, I believe that these colors are the defaults for `magit-diff-added-highlight` for dark displays.  If you customize `magit-diff-added-highlight` and expand for all displays, you will see it.  This is the color that shows up for me when looking at a diff within a magit buffer (just hitting ENTER on a commitish for example).

I don't know why these are being used in my case and not in your case.  The faces for `diff-mode` are never used for `magit` buffers as far as I can tell.

**Comment by n3mo** [comment]
@tee3 thanks for looking into your settings. Not sure why we're getting different behavior on magit-diffs. The magit faces described above are not defined in cyberpunk as you point out, so I should be falling back to magit's defaults. Nothing is set in my emacs customization (neither manually in my .emacs.d, nor through emacs Customize functionality), yet my setup behaves unpredictably. It's a rabbit hole I'm likely to go further down once I'm through the busyness of the holiday season.

Whatever the cause, it seems the prudent solution is for cyberpunk to explicitly set these faces to avoid falling back to the apparently unpredictable default behavior. Thanks for your continued feedback and help. I'll let you know when I get this sorted out!

**Comment by tee3** [comment]
@n3mo You know, there are so many variables, I think setting them probably makes the most sense :).  I may give it a try and see what I get.

I've installed both magit and cyberpunk via `package` from MELPA, so I think the load order not very well-defined.  I did try `emacs -Q` in various ways to get things going, but there are so many packages to load, it's a bit hard to control.  How is yours set up?

I tried loading the cyberpunk theme earlier and by default (I usually select it once I'm up and running) to no avail.  magit-2.x sets them, so I would imagine they are often already set in a lot of configurations.

Thanks again and have a Happy Holiday season!

**Comment by tee3** [comment]
I did a little work on this, you can do what you want with it or I can create a pull request if that would be better.  I basically use the `magit-diffstat-added/removed` faces for `magit-diff-added/removed` faces.

https://github.com/tee3/cyberpunk-theme.el/tree/devel-magit-diff

**Comment by n3mo** [comment]
@tee3 thanks for taking a look at this. If you want to create a pull request that would be great, otherwise I can incorporate things manually to take a look. I hope you had a good holiday season--cheers!

**Comment by tee3** [comment]
See https://github.com/n3mo/cyberpunk-theme.el/pull/23 for the pull request.

**Comment by tee3** [comment]
And @n3mo, I did have a nice holiday, thanks.  Hope you did too!

**Comment by n3mo** [comment]
I believe this wraps up the outstanding issues with magit mode. If I'm mistaken or some new problem creeps up feel free to re-open the issue. I'll commit a new version soon to ensure that melpa stable reflects the changes as well. Cheers!
