### ISSUE TITLE
company colors are "bad"/strange?

### ISSUE THREAD

**Issue by habamax** [n3mo/cyberpunk-theme.el#17]
I am not sure if it is intended to be like that but for me they look quite "bad":
<img width="459" alt="scrshot" src="https://cloud.githubusercontent.com/assets/234774/9429290/d7c6d26c-49d3-11e5-94a8-c3a0eeda19f4.png">

**Comment by n3mo** [comment]
Thanks for the feedback. I don't use company myself (which may explain things), but I would be open to this, and other less-supported modes, getting a face lift. I *gladly* welcome suggestions, so if you have ideas of how to make this look better please share!

**Comment by jasminpatry** [comment]
I fixed this by changing company-tooltip-annotation as follows:
```
   `(company-tooltip-annotation ((,class (:inherit company-tooltip :foreground ,cyberpunk-black-3))))
```
(i.e., I added the `inherit` property).

**Comment by n3mo** [comment]
Thanks to @jasminpatry for providing a patch that fixes the black bars---I've been busy the last few weeks and this helped speed things up for everyone. Cheers!
