### ISSUE TITLE
Italics and Underline not appearing in org-mode

### ISSUE THREAD

**Issue by sleepmore** [n3mo/cyberpunk-theme.el#19]
This is with the cyberpunk theme loaded
![screenshot from 2015-11-14 13-51-35](https://cloud.githubusercontent.com/assets/8596459/11165218/5ba9f282-8ad7-11e5-94a6-b9f89d356894.png)
This is without it
![screenshot from 2015-11-14 13-52-35](https://cloud.githubusercontent.com/assets/8596459/11165219/5e8b38e4-8ad7-11e5-9a37-3e57b2d66a04.png)

I was going crazy thinking this was an issue with my bitmap haxor fonts but it turns out that the issue seems to be coming from this theme. I don't know if you consider this a bug not, but either way I was hoping you could at least point me in the right direction to find a quick fix for it.

**Comment by n3mo** [comment]
Thanks for reporting this. Turns out /italics/ wasn't working either. Both are fixed. The fix is available in Melpa and Melpa-stable (as soon as the changes propagate through the system anyway).

Cheers!

**Comment by sleepmore** [comment]
Thanks a bunch!
