### ISSUE TITLE
Font height

### ISSUE THREAD

**Issue by edvorg** [n3mo/cyberpunk-theme.el#21]
Hi. I'm not sure if it's the right place to submit such issue.
I have some distracting problems with this theme because it has different heights for different faces.
It breaks so many things for me, because face are no more of the same size.
I see some strange ordering issues everywhere in emacs and it's expected.
Is there any way to preserve the same font height every where and use theme only for coloring?

**Comment by edvorg** [comment]
Ah I found, sorry, that's the solution.
```elisp
(set-face-attribute 'org-level-1 nil :height 1)
(set-face-attribute 'org-level-2 nil :height 1)
(set-face-attribute 'org-level-3 nil :height 1)
(set-face-attribute 'org-level-4 nil :height 1)
(set-face-attribute 'org-level-5 nil :height 1)
(set-face-attribute 'org-level-6 nil :height 1)
(set-face-attribute 'org-level-7 nil :height 1)
(set-face-attribute 'org-level-8 nil :height 1)
(set-face-attribute 'sp-show-pair-match-face nil :height 1)
```

**Comment by n3mo** [comment]
That's interesting--cyberpunk shouldn't touch your font height at all. I haven't heard any other complaints, and I use org mode daily with no weird height issues. Is it possible that some other package is causing the need for this fix on your setup? Without applying your solution, do you get this behavior using emacs -Q with just cyberpunk enabled?

**Comment by edvorg** [comment]
The problem here is with monospaced fonts. Bigger height also means bigger width.
E.g. code indentation looks very ugly, but you very right. I have a package which uses org heading faces to colorize parens. So I had very strange behaviour.

**Comment by edvorg** [comment]
I fixed it btw. Just added and advice on load-theme function.
