### ISSUE TITLE
racket-mode is very saturated

### ISSUE THREAD

**Issue by winny-** [n3mo/cyberpunk-theme.el#22]
Hi,

Not sure if this is a feature, but it looks like the default colors kind of work against racket-mode. What do you think?

![2015-12-14-132914_976x1105_scrot](https://cloud.githubusercontent.com/assets/3893828/11791455/c0998ec2-a266-11e5-9e3e-acad93515349.png)

**Comment by n3mo** [comment]
Very much *not* in the spirit of cyberpunk. I'm working on a redesign now that will improve the consistency of the cyberpunk experience across many modes, including racket-mode. Stay tuned...

**Comment by n3mo** [comment]
I've committed an update which makes racket-mode look much more in-line with the cyberpunk theme. I use scheme-mode a lot, and it's notably less colorized than racket-mode, which appears to highlight more things (e.g., variables vs function names). Try switching between the two and let me know what you think. If this looks good, I'll tag a release for melpa-stable

**Comment by winny-** [comment]
It's looking a lot better:

![2015-12-14-232936_1124x1130_scrot](https://cloud.githubusercontent.com/assets/3893828/11802845/9cb048da-a2ba-11e5-815a-fcbc6dd2707d.png)

Oddly `file` and `private` are highlighted the same color as the function calls. That's probably an issue with racket-mode.

Otherwise it's looking great!

**Comment by n3mo** [comment]
It does indeed seem to be an issue with how racket-mode identifies variables vs function calls. I hope you like the new look--let me know if you run into other unsightly coloring!
