### ISSUE TITLE
Couldn't find it in melpa-stable

### ISSUE THREAD

**Issue by anujdeshpande** [n3mo/cyberpunk-theme.el#27]
Emacs version on Mac OS Sierra 10.12.3
```
~$ emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
~$
```

I point to melpa-stable using - 
```
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```
It finds the package alright, but then 
```
https://stable.melpa.org/packages/cyberpunk-theme-1.17.el: Not found
```
Got around it by loading the `.el` locally, but would love to let emacs manage it.

Thanks for the theme btw !

**Comment by n3mo** [comment]
Hi @anujdeshpande! The URL you link to is indeed not found. However, the current stable release seems to have a working URL:
```
https://stable.melpa.org/packages/cyberpunk-theme-1.18.el
```
Is there a reason you're trying to use the older version?

**Comment by anujdeshpande** [comment]
My bad - package-refresh-contents fixed it.

**Comment by n3mo** [comment]
No problem--thanks for closing the issue.
