### ISSUE TITLE
Way to enable transparency?

### ISSUE THREAD

**Issue by computersarecool** [n3mo/cyberpunk-theme.el#32]
I really like this theme but when I use it I lose transparency.

I am using emacs from a terminal that is set to transparent.  If I load emacs without this theme, the background is transparent.

However, when I load this theme, the background is solid black with no transparency.  Is there a way to change this?

**Comment by n3mo** [comment]
I suspect this may have to do with how transparency is achieved on your system (although there could be something that cyberpunk could do to help). For example, I'm using the i3 window manager with [compton](https://github.com/chjj/compton) as my compositor which handles my window opacity. With that setup, if I run emacs in a terminal I have a transparent background with cyberpunk theme loaded (it "just works" for me). 

I know of, but have limited experience with the fact that different terminals and window compositors have different methods of solving the transparency problem. There is some information on [EmacsWiki](https://www.emacswiki.org/emacs/TransparentEmacs) that may address your problem. Can you confirm if those tricks work for you. If not, could you share your setup (Terminal, etc.) for how you're achieving transparency with emacs in a terminal. Also, do other color themes work after manually loading them?

**Comment by computersarecool** [comment]
I see (sorry for the late reply).  I am using Gnome Terminal.

If this were related to how transparency is achieved on my system then I would think there wouldn't be transparency when I do not load cyberpunk but there is.

As soon as I load cyberpunk that transparency goes away.

I tried all the options in the wiki, but some, for isntance `xterm -tn xterm-256color -e emacs -nw` do not ever have transparency.

**Comment by n3mo** [comment]
Can I ask how you are obtaining transparency in gnome terminal? From what I understand gnome terminal has dropped support for transparency. I also use gnome terminal, but as I stated before I achieve transparency via the Compton window compositor. 

Can you try adding the following line to your cyberpunk-theme.el file, and then reloading/restarting? Does removing the background set by cyberpunk allow your terminal's transparent background to show?
````lisp
(set-background-color nil)
````

**Comment by computersarecool** [comment]
I just enable transparency in the Gnome terminal options (see image). Everything else is an Ubuntu / LDM default.

I tried adding the line to the cyberpunk.el file but nothing changed (see image).

![screenshot from 2017-10-22 21-30-16](https://user-images.githubusercontent.com/5414692/31872394-6d0b0d64-b770-11e7-813d-aa89872388bd.png)

**Comment by n3mo** [comment]
So months later (apologies--if only life could be spent entirely on development), I somehow now realize that I completely missed your (very good) point that Emacs transparency is working for you so long as you are not using the cyberpunk theme. Thanks for your patience with my bone-headed questions. Anyway, that's strange indeed, especially given that transparency does work for me with this theme (although I am running a different distro, window manager, and compositor than you). Can you let me know a few themes do work with transparency for you?

**Comment by computersarecool** [comment]
I now use the desktop Emacs on Linux and transparency works so we are good to go here. Thanks!
