### ISSUE TITLE
fringe is white

### ISSUE THREAD

**Issue by hyOzd** [n3mo/cyberpunk-theme.el#37]
When I use cyberpunk theme fringe color is always white. If I switch to a dark theme such as `tango-dark` and switch back to cyberpunk theme it stays dark. So it seem cyberpunk doesn't set the fringe color.

Emacs 25.3.2

**Comment by n3mo** [comment]
Strange--I cannot replicate the white fringe color issue when running either in the terminal or GUI (on Arch Linux or OS X). Despite that, you're correct--the fringe was not being set explicitly when it should have been. Now it is--cheers!

**Comment by hyOzd** [comment]
@n3mo thanks for the fix.
