### ISSUE TITLE
Magit commit numbers not visible in region

### ISSUE THREAD

**Issue by Ambrevar** [n3mo/cyberpunk-theme.el#44]
In Magit Status, when the point is on a commit (e.g. in the "Recent commits" section) the commit number becomes unreadable.

Same with Magit Log.

Any fix?

**Comment by PuercoPop** [comment]
@Ambrevar check my open PR

**Comment by Ambrevar** [comment]
I don't see any PR :p

**Comment by emacsomancer** [comment]
https://github.com/n3mo/cyberpunk-theme.el/pull/41

**Comment by n3mo** [comment]
Merged. Thank you for your contribution (and patience). This is a great, and much-needed improvedment!
