### ISSUE TITLE
Fix Magit diff hunk headings + diff contrast

### ISSUE THREAD

**Issue by Ambrevar** [n3mo/cyberpunk-theme.el#45]
Magit diffs are hard to read for 2 reasons:

- The unselected diff hunk heading background is black, thus it's hard to visualize the different hunks.  Fix:

```elisp
          (set-face-background 'magit-section-highlight cyberpunk-bg-1)
          (set-face-background 'magit-diff-hunk-heading cyberpunk-bg+1)
          (set-face-background 'magit-diff-hunk-heading-highlight cyberpunk-bg+2)
          (set-face-background 'magit-diff-hunk-heading-selection cyberpunk-bg+2)
```

- The "added" diff is blue on green with low contrast which makes it very hard to read.  Quick workaround: increase the contrast a little bit:

```
(set-face-background 'diff-refine-added cyberpunk-green-2)
```

**Comment by Ambrevar** [comment]
Friendly ping :)

**Comment by n3mo** [comment]
Thanks for the friendly reminder. Issue hopefully addressed!

**Comment by Ambrevar** [comment]
Sorry, where is it addressed?

**Comment by n3mo** [comment]
Here's the [commit](https://github.com/n3mo/cyberpunk-theme.el/commit/5b8130e174343478c53b91fd22c98352d3815930#diff-a4ec90e68cd38f9e477e101ddc770e61).

The version bump will take some time to percolate to MELPA if you're waiting for the change there.

Cheers!

**Comment by Ambrevar** [comment]
Thanks a lot!
