### ISSUE TITLE
Change lazy-highlight (search hits) to underline

### ISSUE THREAD

**Issue by Ambrevar** [n3mo/cyberpunk-theme.el#46]
Currently search highlighting displays yellows blocks which are rather displeasing to the eye in my opinion.

The following turns it to yellow underlining:

```elisp
(set-face-attribute 'lazy-highlight nil
                          :underline '(:color "yellow")
                          :foreground 'unspecified
                          :background 'unspecified)
```

**Comment by n3mo** [comment]
Stylistically, this would be an interesting and minimal choice for a theme. My concern with this change is that search is such a common use function that this change is likely to affect many users, including myself, who have been trained for years to look for those color pops. Perhaps this kind of individual preference change is better reflected in your own init file? You could put your code snippet anywhere after the cyberpunk theme is loaded to make that change live on your system.

**Comment by Ambrevar** [comment]
Fair enough! :)

What about adding this example to the README then?

**Comment by Ambrevar** [comment]
@n3mo Friendly ping :)

**Comment by n3mo** [comment]
Example added to the README--cheers!

**Comment by Ambrevar** [comment]
Excellent, thanks!
