### ISSUE TITLE
Color palette revision or addendum

### ISSUE THREAD

**Issue by anoduck** [n3mo/cyberpunk-theme.el#50]
Not sure where the color palette came from, but it is not what most people would consider to be cyberpunk. It might behoove you to create a secondary palette for selection that is more true to the genre.

![wallpapersden com_woman-in-cyberpunk-city_2560x1600](https://user-images.githubusercontent.com/9925396/212299880-68d97c94-453a-41d4-9c29-ffc9e1ffe755.jpg)

Don't hate me, just a suggestion...

**Comment by n3mo** [comment]
No hate! I think you're not alone, and this is something I've considered. I think the presence of yellow in particular is the problem. One possibility is to split this into two themes--one that sticks with the current palette and another that revises things closer to the colors in your example image. The difficult thing is always that changing one thing for someone causes changes that bother someone else. Hopefully I'll get some free time soon to implement this or another solution. Thanks for the feedback!

**Comment by anoduck** [comment]
@n3mo Wow, incredibly thoughtful and open to feedback. You are absolutely spot on with considering elimination of yellow. Doom emacs has outrun-electric, but it doesn't hit the mark. I have very slowly, and I do mean very slowly, been working on creating my own rendition of the cyberpunk/synthwave theme, calling it "tropical neon". Honestly, it makes my head spin, there are so many colors to match and find analogous colors for. 

Thanks for understanding. You are a real trooper.

**Comment by anoduck** [comment]
@n3mo I found this repo, and immediately thought I should share it to provide some inspiration. It is one seriously awesome setup. Cheers.

https://github.com/VaughnValle/elektropunk
